# Generated by Django 4.1.7 on 2023-03-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utility',
            old_name='utilityname',
            new_name='name',
        ),
    ]
