# Generated by Django 4.1.7 on 2023-03-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_utilityname_utility_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='reading',
            field=models.PositiveIntegerField(),
        ),
    ]
