# Generated by Django 4.1.7 on 2023-04-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_reading_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
