# Generated by Django 4.1.7 on 2023-04-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_utility_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
