# Generated by Django 4.1.7 on 2023-04-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_reading_created_alter_reading_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
