# Generated by Django 4.2 on 2023-04-26 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_invoice_approved_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.CharField(default='consumer', max_length=15),
        ),
        migrations.AddField(
            model_name='utility',
            name='rate',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='utility',
            name='supplier',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to=settings.AUTH_USER_MODEL),
        ),
    ]
