# Generated by Django 4.2 on 2023-04-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_utility_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='supplier',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='base.profile'),
        ),
    ]
