# Generated by Django 4.2 on 2023-04-27 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='base.profile'),
        ),
    ]
