# Generated by Django 4.2 on 2023-04-27 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_utility_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='meternumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumersignature', models.ImageField(upload_to='')),
                ('suppliersignature', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='base.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
            ],
        ),
    ]
