# Generated by Django 4.2 on 2023-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='arrears',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
