# Generated by Django 4.2 on 2023-05-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_profile_arrears'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoiceNo',
            field=models.AutoField(default=100060, primary_key=True, serialize=False),
        ),
    ]
