# Generated by Django 4.2.1 on 2023-05-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_contract_consumersignature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='connectiondate',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
