# Generated by Django 4.2.1 on 2023-06-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_profile_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prepayment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
