# Generated by Django 4.2.1 on 2023-06-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_reading_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previousarrears',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
