# Generated by Django 4.2.1 on 2023-06-21 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0034_alter_reading_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
