# Generated by Django 4.2.1 on 2023-06-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_contract_status_alter_contract_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='consumersignature',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='suppliersignature',
            field=models.TextField(null=True),
        ),
    ]
