# Generated by Django 4.2.1 on 2023-06-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_contract_consumersignature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='meternumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='rate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(default='new', max_length=15),
        ),
    ]
