# Generated by Django 4.2.1 on 2023-06-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_contract_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(default='new', max_length=25),
        ),
    ]
