# Generated by Django 4.2.1 on 2023-07-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='readingimage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
