# Generated by Django 4.2.1 on 2023-07-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_contract_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='refundabledeposit',
            field=models.BooleanField(null=True),
        ),
    ]
