# Generated by Django 4.2.1 on 2023-07-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_contract_refundabledeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='meternumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
